### PR TITLE
Remove failed assert.

### PR DESCRIPTION
**Pull request by polina-c**
Failure: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20framework_tests_libraries/46558/overview

### CODE REVIEW

**Review by jonahwilliams — CHANGES_REQUESTED** [review]
It doesn't seem like you should be removing an assert that is checking that leak tracker is working?

**Comment by polina-c** [comment]
> It doesn't seem like you should be removing an assert that is checking that leak tracker is working?

This assert should never fail because of tracked objects. If it failed, this means there is algorithmic error. And it seems it failed because of duplicated hash code. Leak tracker expects duplicated, but it seems not very reliably. And this story is not easy to test.

I plan to refactor leak_tracker to stop counting on hashes. But for now I do not want this noise in flutter test failures. There is enough flakiness in flutter itself :)

Makes sense?

**Review by jonahwilliams — COMMENTED** [review]
I guess, but seems like a pretty severe issue. if its not happening frequently, you might just want to leave it as is

**Comment by polina-c** [comment]
> I guess, but seems like a pretty severe issue. if its not happening frequently, you might just want to leave it as is

Maybe. Lets have this PR ready to merge. I will do some adjustments and maybe we will not need it.
Converted to draft.

**Comment by polina-c** [comment]
I updated leak_tracker to stop identifying objects by hash codes. So, this PR should not be needed.

**Pull request closed without merging**
