### PR TITLE
Fix `labeler.yml`

### PR DESCRIPTION
**Pull request by mosuem**
See https://github.com/dart-lang/native/pull/873

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by polina-c** [comment]
@devoncarew , can you take a look. I am not experienced enough in this area.

**Review by devoncarew — APPROVED** [review]
👍

**Comment by polina-c** [comment]
@mosuem , can you fix failure of 'Pull Request Labeler / label (pull_request_target)'?

**Comment by devoncarew** [comment]
The failure for the `Pull Request Labeler / label` bit won't be fixed until this PR lands. I believe it won't use the new config until it's on master.

**Comment by polina-c** [comment]
> The failure for the `Pull Request Labeler / label` bit won't be fixed until this PR lands. I believe it won't use the new config until it's on master.

Ok, merging in spite of failures.

**Pull request merged**
